- app/styles/components/c_layer_panel.scss
- app/styles/components/c_map.scss
- app/styles/components/c_vessel_panel.scss
- app/styles/index.scss
This PR changes the position of the vessel panel. Now it doesn't overlap any other UI elements and is vertically scrollable if the height of the device is small. Additionally, when it would be displayed behind the "layer" panel when expanded.
> Improves the styles so the vessel panel doesn't overlap any other UI

- app/index.html
- app/src/components/app.jsx
- app/src/components/map/DatePicker.jsx
- app/src/components/map/Timeline.jsx
- app/styles/_base.scss
- app/styles/index.scss
- config/webpack.config.js
- package.json
Adds full date pickers to the timeline.
Notes:
- uses https://github.com/Hacker0x01/react-datepicker, which has a de facto dependency to moment.js. Eventually we could swap all our dates to moment (except in d3), could simplify the code a bit in Timeline.jsx
- needed to add a webpack css loader to load react-datepicker css
- that `> div, > div > div, > div > div > div {` bit needed to be removed because it was fucking up react-datepicker layout. That's what happens when you style divs directly.
> date pickers

- app/src/actions/faq.js
- app/src/components/blog.jsx
- app/src/components/blog_detail.jsx
- app/src/components/faq.jsx
- app/src/components/shared/CoverPrimary.jsx
- app/src/components/shared/CoverSecondary.jsx
- app/src/constants.js
- app/src/containers/faq.js
- app/src/index.jsx
- app/src/reducers/faq.js
- app/src/reducers/map.js
- app/src/routes.jsx
- app/styles/components/c-cover-page.scss
- public/faq.json
I implemented the yet unstyled and undesigned FAQ section. I am reusing the react-safona component from the map for the accordion (the WF had one, there is still no design for this page). The current result is showing very little content, but it's a CSS issue, the data is in the DOM.
I extracted the header from the Blog/BlogDetails as reusable components.
The FAQ is being loaded from a JSON file in the public folder - loading from an API is not on the current roadmap, but this way making that change is as easy as it gets.
@hectoruch take a close look at CoverMain and CoverSub - these are basically the same files you created, but decoupled from the blog, so that they can be reused in other pages. Study this pattern and try to use it in the future.
> FAQ section

- app/src/components/map.jsx
Really a simple fix but it's a simple issue: do not redraw track layer at drag end if no track information is available (no vessel has been clicked)
> fixed empty track at drag end

- package.json
- scripts/get-scss-files-to-push.sh
- scripts/pre-push
I was pissed off by those 900+ sass errors, so this is a proposal: the `lint-sass` npm task will now only lint sass files that have been edited or added (compared to origin/master), but in exchange the pre-push hook will now exit whenever one of the two linters fail.
> enforce css linter for edited/new files

- app/src/actions/user.js
Use localStorage instead of sessionStorage to store oAuth token over tabs/windows.
> store auth token permanently

- app/src/components/Definitions.jsx
- app/src/components/Home/CoverPage.jsx
- app/src/components/Home/Steps.jsx
- app/src/components/Shared/ContentAccordion.jsx
- app/src/components/Shared/CoverPrimary.jsx
- app/src/containers/ContentAccordion.js
- app/src/lib/AccordionGF.jsx
- app/src/lib/Utils.jsx
- app/src/routes.jsx
- public/definitions.json
- Created `ContentAccordion ` container to allow router management (`push` function).
- When the user clicks on a item, the url will be updated with the new slug entry.
- Back and forward navigation works smoothly.
- Added `slug` property in JSON file: this way we avoid use regexp and other problems generated because inconsistent format. 
The default library didn't include a `componentWillReceiveProps ` function that allows us update the component with new props, that's why we have to create our "own" accordion and overwritting the function to allow us update the component (that allows the accordion being updated if you want to go back to see your las entry).
Probably you will have doubts about this, talk to me if need!
Kudos to Ra for helping me with this!
> implemented terms by url

- app/src/routes.jsx
- package.json
This PR forces the app to scroll to top when routing so the user won't stay at the bottom of the page when its content changes. The solution uses a new library called [react-router-scroll](https://github.com/taion/react-router-scroll) which permits a per-route-transition decision whether the page should be scrolled.
The function `shouldUpdateScroll` which is the one deciding of the scroll, forces it to happen unless the developer specifies a list of regexes (inside the array `regexes`) for which, if the previous page and the next one match one of them, then the page won't be scrolled. An example of how this is handle can be found in PREP [here](https://github.com/resource-watch/prep-app/blob/develop/app/scripts/routes.jsx#L76-L79).
> Forces the app to scroll to top when routing

- app/src/components/AuthMap.jsx
- app/src/containers/Map.js
- app/src/containers/MapIFrame.js
- app/src/routes.jsx
This PR implements Pivotal's task [#128974855](https://www.pivotaltracker.com/story/show/128974855). We want the map's URL with workspace specified to go from
`http://gfw.org/map?workspace=123`
to
`http://gfw.org/map/workspace/123`.
> Workspace id is now part of the map's route

- app/src/routes.jsx
This PR fixes an issue where the page would scroll to top each time the user would click on an item of the definitions page. To solve it, it defines an exception on the configuration of `react-router-scroll`.
> Prevents the Definitions page to scroll to top

- .eslintignore
- app/src/components/Shared/Header.jsx
- app/src/util/assignPolyfill.js
- config/webpack.config.js
- package.json
This polyfill brings this:
`This means you can use new built-ins like Promise or WeakMap, static methods like Array.from or Object.assign, instance methods like Array.includes, and generator functions (provided you use the regenerator plugin). The polyfill adds to the global scope as well as native prototypes like String in order to do this.`
from [https://babeljs.io/docs/usage/polyfill/](https://babeljs.io/docs/usage/polyfill/)
> implemented basic polyfills

- config/webpack.config.js
Now css-modules generate readable classes names
Before: b6nQPTSi3Ns04Sp4VrZA6 
Now: c-header__contain-nav___b6nQP
> Gift for @andresgnlez. Fix problem in generated classes names. Now generate a readable class name :)

- app/src/components/Shared/Accordion.jsx
- app/styles/components/shared/c-content-accordion.scss
This PR brings small changes to the accordion following Héctor's comments:
* Change the direction of the rhombus to follow the design
* Add a padding to the right of the titles so the rhombus doesn't overlap them
* Vertically center the rhombus
[Pivotal task](https://www.pivotaltracker.com/story/show/129783887)
> Improves the responsiveness of the accordion and the position of its rhombus

- app/src/components/Shared/Rhombus.jsx
- app/styles/components/shared/c-rhombus.scss
This PR mainly fixes an issue where the Rhombus' arrow wouldn't be centered. Before, it would be displayed like that:
Additionally, it prevents the element to get `null`classes and simplifies the CSS.
[Pivotal task](https://www.pivotaltracker.com/story/show/129787117)
> Fixes the position of the arrow within the rhombus

- app/styles/components/c-info-map-content.scss
This PR fixes an issue where the homepage could be horizontally scrolled on mobile devices (at least iOS) because the width of a section was fixed to dimension larger than the permitted one.
[Pivotal Task](https://www.pivotaltracker.com/story/show/129919141)
> Removes the horizontal scroll from the homepage

- app/src/components/Home/CoverPage.jsx
This PR makes the homepage great again. The issue was that the homepage would freeze when resizing the browser's window. The reason is that the resize callback would be executed on each event instead of being debounced.
@hectoruch When you resize the window, the resize event is sent at an incredible frequency, we thus need to debounce. If we don't do it, the state of CoverPage will keep on being updated and, if I'm not wrong, React will wait for it to "stabilize" before rendering the component again. Also, because the state updates are stored in a queue, we just fill the memory too fast, without emptying it. That's why the page was really slow.
[Pivotal Task](https://www.pivotaltracker.com/story/show/129830859)
> Debounces the resize callback of CoverPage

- app/src/components/Map.jsx
Pivotal task: https://www.pivotaltracker.com/story/show/134395665
The error was produced because `ClusterAnimation`-typed layers were trying to access to the method `isVisible` of CARTODB layers.
Also, the property `addedLayers ` of `this.state` was initially an array. Now it's an object. Otherwise, when the app added layers with methods like `addCartoBasemap` or `addCartoLayer`, instead of pushing the layer into the array, the layer was setted as a property of the array, which can be really confusing.
> Fixed error related with vessel layers

- app/src/components/Map/Timebar.jsx
- app/src/constants.js
Limit the display range to 6 months to avoid locking the UI for too long.
> limit inner extent to 6 months

- app/src/components/Map.jsx
- app/src/components/Map/Timebar.jsx
- config/webpack.config.js
This shaved off 5 seconds from the build time, but it's still taking 18 seconds on a cold webpack cache
> optimize webpack image processor

- app/src/components/Map/Timebar.jsx
Currently, if you extend the inner brush beyond the limit (configured to 6 months), it snaps back to the old value. This is kind of annoying, and I believe that it should instead stay at the max width of the inner range
> Improce inner time range extend behavior

- app/src/components/Map/Timebar.jsx
- app/styles/components/map/c-durationpicker.scss
Timebar should be behind sidebar, because you can always collapse sidebar to let the timebar show up.
Also it's way simpler to fix.
> fixed timebar/sidebar overlap issue

- app/src/components/Map/Timebar.jsx
For some reason, when I clicked on "Back to homepage" link, in the no-login modal, it triggered the `componentWillUnmount` function of the timebar "breaking" the link and forcing to the user to click a second time to go back to the homepage.  
It brokes because all variables used on that function weren't initialized. Now, I ask if the timebar is already initialized before do anything.
> Avoid unmount component when its not initialized

- app/src/components/Map/DurationPicker.jsx
- app/src/components/Map/Timebar.jsx
This PR filters predefined range times based on the current timebar. In the above picture the timebar range is lesser than a month, that's why in the predefined range times only the options `15 days` and `7 days` are available.
> Filtered predefined range time based on timebar current range

- package.json
Personally I don't like the idea of pointing to a specific branch but as we don't know when the owner of the project will merge it this is the only solution meanwhile. If the branch is merged we'll have to change this value to the previous one again.
With this change, Safari accordion animations are fixed for Safari desktop, iPad and iPhone.
Don't forget to remove your `react-sanfona` folder in `node_modules` and `npm i` to install the new version.
> Temporal fix for Safari accordion animations

- app/src/components/Map/VesselInfoPanel.jsx
- app/styles/components/c-vessel-info-panel.scss
Pivotal task: https://www.pivotaltracker.com/story/show/136898497
At this moment, API is NOT providing RFMO links info so I faked them temporally to implement and style them and take a picture of how it would look. Fields are based on [this comment](https://www.pivotaltracker.com/story/show/136898497/comments/159307455).
> Added RFMO links

- app/src/components/Map/VesselInfoPanel.jsx
- app/styles/components/c-vessel-info-panel.scss
Pivotal task: https://www.pivotaltracker.com/story/show/136898451
The link wasn't showing because they removed the `link` params which provides it.
As the Marine Traffic link is composed by an static part and the `MMSI` is fine for us to build the link ourselves. Enrique is talking about sending the info through API, but this is not necessary if the format is always the same. Let me know your opinion.
> Restored Marine Traffic link

- app/src/actions/heatmap.js
- app/src/actions/helpers/heatmapTileData.js
- app/src/components/Layers/MapLayers.jsx
- app/src/components/Layers/TiledLayer.js
- app/src/containers/Layers/MapLayers.js
- public/workspace.json
Replaced our hacky coordinates calculation with standard GMaps APIs, which will be slower, but it's done 'offline' (only once after tile loading) so it's barely visible (especially since we are still loading all years at once), but we might want to try to revise that at a later stage
> fixed offset issue at high z levels

- app/src/components/Map/VesselInfoPanel.jsx
This has not been tested yet, as the API is not returning data for guests. Test + merge
> Limit pinning vessels to authed users

- app/src/components/Map/Share.jsx
- app/styles/components/map/c-share.scss
Facebook and G+ button don't work because of localhost. Twitter one just copy and paste the URL argument, it can be customized  with a text. This functionality just share, it doesn't track anything or add "likes" or "+1" in cases of Facebook and G+.
> Added social functions

- app/src/components/Shared/Toggle.jsx
- app/styles/components/map/c-layer-library.scss
- app/styles/components/map/c-welcome-modal.scss
- app/styles/components/shared/c-toggle.scss
This PR includes following fixes:
- Issue where toggle's width in safari wasn't the minimum needed.
- Removes `overflow: overlay`: _apparently has been deprecated for some time now_.
- Issue where scroll down gradient blocked toggles.
> Fix: toggle style improvement

- app/src/components/Layers/MapLayers.jsx
This PR address an issue where the map crashed if resized immediately after loading.
> feature: resize after load crash

- app/src/actions/layers.js
Removed a hack to load the latest version of the fishing effort layer.
> Remove temp tileset loading workaround

- app/src/components/Layers/CustomLayerWrapper.js
- app/src/components/Layers/MapLayers.jsx
- app/src/constants.js
This PR fixes an issue where large layers (global ones specially) were zoomed out and map went gray.
> prevents zoom on large spanned custom layers

- app/src/actions/timebar.js
This PR fixes an issue that ocurred when loading timebar json files from timezones that were still in 2011 at `2012-01-01 UTC` time.
> Fix: transforms dates to utc

- app/src/constants.js
Requires less precision when clicking on heatmap points.
> increased heatmap click tolerance

- app/src/reducers/report.js
Seems like cartodb doesn't support uppercase identifiers in certain
fields. When we lookup the `reportingId` field, cartodb always returns
`reportingid` (lowercase i), and thus the app never finds that field,
defaulting to using the `cartodb_id` field instead on report requests.
This commit changes the field lookup to be `reporting_id` instead,
which doesn't have this problem and it also makes it more consistent
with the rest of the identifiers we have on carto.
> Fixes broken reporting id field lookup.

- app/src/actions/filters.js
- app/src/actions/vesselInfo.js
This prevents the timebar extents from updating when user is clicking on a vessel, it should now only happen when using the search feature.
Additionnally, adds some sanity by moving the fit timebar extents logic from the vesselInfo actions to the filters actions.
> Only update temporal extent on search

- app/src/actions/heatmap.js
- app/src/actions/layers.js
- app/src/actions/search.js
- app/src/actions/vesselInfo.js
- app/src/actions/workspace.js
- app/src/components/Layers/MapLayers.jsx
- app/src/components/Map/RecentVesselsModal.jsx
- app/src/components/Map/SearchPanel.jsx
- app/src/components/Map/SearchResult.jsx
- app/src/containers/Map/RecentVesselsModal.js
- app/src/containers/Map/SearchResult.js
- app/src/reducers/vesselInfo.js
- app/src/util/calculateLayerId.js
- public/workspace.json
We had an implicit requirement that a fishing layer's id in the workspace had to equal the tileset id. This removes that restrictions, which should help on some scenarios. It also puts us 1 step closer to multi-layer vessel searches.
overall, I feel like the map.tilesetUrl and map.tilesetId states should be deprecated.
> decouple layer id from tileset id

- CHANGELOG.md
- app/src/components/Map.jsx
- app/src/containers/Map.js
because we were using an array to map the map center in props, differences were never detected. So loading a map from workspace would result in the center being 0,0
this should fix the issue
> Fix map center loading

- CHANGELOG.md
- app/src/actions/search.js
- app/src/actions/vesselInfo.js
- app/src/actions/workspace.js
Fix one bug, get one awesome feature free!!!
Clarifying: the vessel track rendering based on search results seems to still be coupled to the workspace's "tileset" param. This PR aims at decoupling them, by coupling it to the layer's tilesetId. Add an iteration, and we have multi-layer search.
I actually have NOT tested this with multiple layers, which we should do. But hopefully shouldn't be too much work to get there from these changes.
> Multi-layer search

- CHANGELOG.md
- app/src/reducers/vesselInfo.js
- fallback title when vesselname is not present (https://basecamp.com/1756858/projects/12049853/todos/307159441)
- fixed a bug where typing a custom would be very slow when pinned track was visible
> pinned vessel title fixes

- CHANGELOG.md
- app/src/components/Layers/MapLayers.jsx
Fishing layers that have visible: false on the workspace are failling to load if you enable them in the layers panel. This fixes the issue
> Fix loading of disabled fishing layer

- CHANGELOG.md
- app/index.html
- app/src/actions/literals.js
- app/src/actions/workspace.js
- app/src/components/Map/BasemapPanel.jsx
- app/src/components/Map/Share.jsx
- config/webpack.config.js
This stops forcing the root html file to load the js and css bundles from '/', so they should be loaded with a relative path now.
> removed webpack absolute path

- README.md
- app/index.html
- app/src/actions/literals.js
- app/src/components/Map/BasemapPanel.jsx
- config/webpack.config.js
- package.json
This includes a couple of changes we required for our production release:
* Makes webpack build assets using a public path. This is configurable through a `PUBLIC_PATH` env variable. If no `PUBLIC_PATH` is set up (such as in your heroku environment, or in the local development environment), webpack handles it by making requests to the root.
* Configures `HtmlWebpackPlugin` to load the index template through `html-loader`, instead of the custom built-in, ejs-like loader. This allows us to resolve asset location inside the html template so that webpack can actually resolve to the proper location (including public path configurations and cache busting).
* Exposes the `PUBLIC_PATH` env variable with the `DefinePlugin` so that local programmatic requests (such as the literals and the basemap …
> Application loaded on different public path

- CHANGELOG.md
- app/src/actions/vesselInfo.js
- app/src/components/Map/PinnedTracksItem.jsx
- app/src/components/Map/VesselInfoPanel.jsx
- app/src/constants.js
- app/src/containers/Map/PinnedTracksItem.js
- app/src/containers/Map/VesselInfoPanel.js
- app/src/reducers/vesselInfo.js
- app/styles/components/c-vessel-info-panel.scss
- public/workspace_vms.json
Until now, vessel details used a hardcoded strucutre. since we now have multiple layers, each with different vessel info details, we need to rely on each vessel layer header to tell us which field and what type it is.
> Add support for dynamic vessel info

- app/src/reducers/vesselInfo.js
- package-lock.json
We are doing deep cloning way more often than needed. For example, pinning/unpinning a vessel can take from 0.5 to a couple seconds because of it.
Silly approach (implemented here): replace all cloneDeep calls with plain clone calls. Risky but it seems to work, as I think we never really compare the track array itself, only the vessel object
Pro approach (maybe for later): keep tracks separated from vessel details in the reducer, and use an id for cross-access. 
thoughts?
> Prevent unecessary cloning of vessel tracks on vessel edits

- app/src/filters/components/FilterPanel.jsx
- app/styles/components/map/flag-filters.scss
The padding is different in filters and group filters. Now is fixed.
> Fix padding in single filters submenu

- app/src/config.js
- public/workspace.json
This is a quick hack so that the MPARU color is the same as the one used in the Carto layer:
The way we deal with colors in the app state seems pretty fragile to me. How do you feel about removing hue (legacy from old UI) and named colors everywhere and unify using only hex colors strings?
(we'd only need some mechanism to convert hues to colors from a loaded workspace)
> How do we store colors in app state?

- app/src/actions/workspace.js
- app/src/components/Layers/HeatmapLayer.js
- app/src/constants.js
- app/src/filters/components/FilterGroupForm.jsx
- app/src/filters/components/FilterGroupPanel.jsx
- app/src/filters/containers/FilterGroupForm.js
- app/src/filters/containers/FilterGroupPanel.js
- app/src/filters/filterGroupsActions.js
- app/src/filters/filterGroupsReducer.js
- app/src/filters/filtersActions.js
- app/src/filters/filtersReducer.js
- app/src/layers/layersActions.js
- app/src/util/getFlagFilterGroupValues.js
- removed duplicated logic in FilterGroupForm. The container now has logic to prepare the data coming from the stores for the component to render.
- made FilterGroupForm a dumb component: it doesn't handle its own state, and directly calls actions on the store for every modification of the currently edited filter.
- creating a new filter group, with initial state, has an explicit action in the actions rather than inside the component
- added support for aliasing filters (ie filters that have the same id but apply to a different field depending on the layers, for example flag --> flag_id or category)
- moved flag options generation code to an util, they are now generated once in a constant
- removed legacy filter code as well as support for headers without filter information (default …
> Refacto filters modal

- app/src/timebar/timebarActions.js
Production broke because of a missing timebar json file, this makes it resilient.
> added fail safe for loading timebar json files

- package.json
We have moved the GFW map from the Vizzuality organization to GlobalFishingWatch one. We have also migrated the dependent repositories. This PR takes care of the changes needed in the package.json in order for the project to use the correct paths.
> Changes on package.json to reflect repository location change

- README.md
- app/src/analytics/analyticsMiddleware.js
- app/src/app/appActions.js
- app/src/app/appReducer.js
- app/src/components/AuthMap.jsx
- app/src/components/ModalContainer.jsx
- app/src/containers/AuthMap.js
- app/src/containers/MapContainer.js
- app/src/containers/ModalContainer.js
- app/src/index.jsx
- app/src/layers/layerLibraryActions.js
- app/src/mapPanels/leftControlPanel/containers/LeftControlPanel.js
- app/src/reducers/map.js
- app/src/siteNav/components/MenuMobile.jsx
- app/src/siteNav/containers/Header.js
- app/src/siteNav/containers/MenuMobile.js
- app/src/workspace/workspaceActions.js
- config/webpack.config.js
This implements https://github.com/GlobalFishingWatch/GFW-Tasks/issues/648
It can be tested by appending the following workspace override samples to the client's URL:
```
paramsPlainText={"vessels":[[5572477,"516-resample-v2",45017],[3535204,"516-resample-v2",38829]],"view":[6,-3,48],"innerExtent":[1478707468062,1479469642064],"outerExtent":[1477360207737,1480550400000]}
```
Or, using the base64 encoded version:
```
params=eyJ2ZXNzZWxzIjpbWzU1NzI0NzcsIjUxNi1yZXNhbXBsZS12MiIsNDUwMTddLFszNTM1MjA0LCI1MTYtcmVzYW1wbGUtdjIiLDM4ODI5XV0sInZpZXciOls2LC0zLDQ4XSwiaW5uZXJFeHRlbnQiOlsxNDc4NzA3NDY4MDYyLDE0Nzk0Njk2NDIwNjRdLCJvdXRlckV4dGVudCI6WzE0NzczNjAyMDc3MzcsMTQ4MDU1MDQwMDAwMF19
```
Note: this is encoded using `window.btoa` (not sure what should be used server side).
Not implemented but might be …
> Workspace get override

- app/src/actions/heatmap.js
- app/src/actions/vesselInfo.js
- app/src/encounters/encountersActions.js
- app/src/layers/layersActions.js
- app/src/search/searchActions.js
- app/src/tracks/tracksActions.js
- app/src/util/buildEndpoint.js
- app/src/util/heatmapTileData.js
- public/workspace.json
See: https://github.com/GlobalFishingWatch/GFW-Tasks/issues/661
Warning: this PR removes support for layers that don't have an `endpoints` object in their header. I suggest we merge only after deploying the corresponding API changes.
> use header templates to build URLs for tiles, tracks, info, search

- app/src/timebar/timebarActions.js
I have a CORS issue in production (only on Firefox strangely) with the JSON endpoints for Timebar data. When this fails, the layer library does not get loaded which causes the whole app to crash. This is a structural issue that we need to fix later. 
For now this is a simple hotfix that just loads dummy data.
> failsafe to continue loading workspace when timebar data fails

- app/src/mapPanels/rightControlPanel/components/ControlPanel.jsx
- app/src/mapPanels/rightControlPanel/containers/ControlPanel.js
Fix for https://github.com/GlobalFishingWatch/GFW-Tasks/issues/677
> autoscroll when opening vesselInfo or encounters panel

- app/src/search/components/SearchModal.jsx
- app/src/search/components/SearchPanel.jsx
- app/src/search/components/SearchResult.jsx
- app/src/search/containers/SearchModal.jsx
- app/src/search/containers/SearchPanel.js
- app/src/search/searchActions.js
- app/src/search/searchReducer.js
Contains the following fixes related to vessel search:
- consistent ordering of search results (fixes https://github.com/GlobalFishingWatch/GFW-Tasks/issues/717)
- fixed an issue where the number of pages available in paginated search results was always higher than needed, resulting in empty pages
- fixed an issue where words were not highlighted when search contained several words (ie a search for "__TUNA QUEEN__" would not result in highlighting "SOME VESSEL WITH THE WORD __QUEEN__")
> Search results fixes

- app/src/vesselInfo/components/VesselInfoDetails.jsx
Will render any field named 'datetime' as a humanized date/time. Required for VIIRS layer.
> display humanized datetime in vesselinfo

- app/src/encounters/encountersActions.js
Fix for https://github.com/GlobalFishingWatch/GFW-Tasks/issues/749
> Encounters: use workspace layer id as a fallback to layer tilesetId

- config/webpack.config.js
We have a bad configuration setting in the uglifyjs plugin which is causing the app not to load the sourcemaps in production builds even if it should.
> Enables sourcemaps in production builds

- app/src/workspace/workspace.js
- app/src/workspace/workspaceActions.js
- bin/retrieve-workspace.js
- package.json
This adds a script that retrieves the default workspace from V2_API_ENDPOINT and DEFAULT_WORKSPACE env vars, writes it to a JS file that gets compiled in the JS bundle, avoiding having to fetch it at runtime.
The script is automatically triggered when doing `npm install` (so before every deployment).
If the the URL as worskpace id, it will still load it as before.
Also, if LOCAL_WORKSPACE is set, it will override the bundled workspace - this should be for dev purposes only and should not be in env vars used for deployment.
> compile default workspace

- app/src/workspace/workspaceActions.js
- public/workspace.json
This introduce a different `auto` mode for the `timeline` workspace parameter:
```
"timeline": {
"auto": {
"daysEndInnerOuterFromToday": 4,
"daysInnerExtent": 30
}
}
```
When `auto` exists on  `timeline`, it replaces the `innerExtent` and `outerExtent` parameters.
It's possible to also just set `"auto": true`, in which case `daysEndInnerOuterFromToday`(position of the end of the inner and outer extents expressed a number of days from today) and `daysInnerExtent` (length of the inner extent in days) are set to defaults (4 and 30 days).
I believe that this simple approach (rather than using layers headers) works for our use case. It also avoids that very awkward "timeline jump" between app start and all layer headers loaded.
> Auto timeline

- CHANGELOG.md
- app/src/activityLayers/containers/ActivityLayers.js
- app/src/activityLayers/heatmapTilesActions.js
- app/src/config.js
- app/src/layers/layersActions.js
- app/src/map/mapViewportActions.js
- app/src/map/mapViewportReducer.js
Fix for https://github.com/GlobalFishingWatch/map-client/issues/940
Previous behaviour:
User could not zoom beyond z level 10. This value was set on each activity layer header (`max_zoom`) and apparently was always the same for all layers. The client did not correctly handle different zoom levels anyways.
Now:
User can zoom up to a more detailed z level, set arbitrarily as 14.
Removed faulty z level logic, maximum zoom level for loading of tiles is hardcoded at 10. For z levels 11-14, the map will still display activity layers, but with the last available z level (10)
@enriquetuya let me know if per-layer max zoom level is actually required (considering we never had this working on the client side and that it's not trivial to implement)
> High zoom levels handling

- app/src/activityLayers/components/ActivityLayers.jsx
- app/src/activityLayers/containers/ActivityLayers.js
- app/src/config.js
- app/src/map/mapViewportActions.js
- app/src/map/mapViewportReducer.js
- app/src/miniglobe/components/MiniGlobe.jsx
- app/src/miniglobe/components/miniGlobe.scss
- app/src/miniglobe/containers/MiniGlobe.js
Miniglobe viewport outline (red polygon) used to be an approximation; it is now fully accurate, taking projection into account.
Fixes an issue mentioned here:
https://github.com/GlobalFishingWatch/map-client/issues/941
> Miniglobe viewport outline is now accurate

- CHANGELOG.md
- app/src/map/gl-styles/style.json
- app/src/map/mapInteractionActions.js
- app/src/map/mapStyleActions.js
- documentation/workspaces.md
- public/workspace.json
This adds the possibility to directly specify Mapbox GL JSON for workspace layers, allowing pulling layers from CARTO without having to have them specified in the `directory` endpoint nor in the base GL JSON style (use cases described here: https://github.com/GlobalFishingWatch/map-client/issues/932#issuecomment-412865322)
The gist of it is: 
- set up a CARTO table, have it public
- add the SQL query and a bunch of other parameters in the workspace layer `gl` parameter.
This is fully documented, with examples, here: https://github.com/GlobalFishingWatch/map-client/blob/a0e6283d539c75048a4cfa9221797f50d14b9b2b/documentation/workspaces.md
This is the workspace used for tests: https://github.com/GlobalFishingWatch/map-client/blob/a0e6283d539c75048a4cfa9221797f50d14b9b2b/public/workspace.json …
> Workspace gl layers

- CHANGELOG.md
- app/assets/icons/target.svg
- app/src/components/Shared/Icon.jsx
- app/src/components/Shared/Icon.scss
- app/src/components/Shared/IconButton.jsx
- app/src/components/Shared/IconButton.scss
- app/src/encounters/components/EncountersVessel.jsx
- app/src/map/mapInteractionActions.js
- app/src/map/mapViewportActions.js
- app/src/recentVessels/containers/RecentVesselItem.js
- app/src/recentVessels/containers/RecentVesselsModal.js
- app/src/search/containers/SearchResult.js
- app/src/vesselInfo/components/VesselInfoDetails.jsx
- app/src/vesselInfo/components/VesselInfoPanel.jsx
- app/src/vesselInfo/containers/VesselInfoPanel.js
- app/src/vesselInfo/vesselInfoActions.js
- app/src/vesselInfo/vesselInfoReducer.js
- app/src/vessels/components/Vessel.jsx
- app/src/vessels/containers/Vessel.js
- app/src/workspace/workspaceActions.js
- app/styles/_settings.scss
- app/styles/components/info-panel.scss
- app/styles/components/map/item-list.scss
- app/styles/components/shared/accordion.scss
This implements https://github.com/GlobalFishingWatch/map-client/issues/930
- Added buttons to fit the viewport and timebar to vessel tracks (both in pinned vessels list and vessail details panel)
- Removed automatic fit to viewport and timebar when clicking on a vessel search result (can now be done by explicitely clicking the button)
- Clicking the (i) vessel button again now hides vessel details
- Harmonisation of icons
> Fit to track

- CHANGELOG.md
- app/src/map/mapStyleActions.js
- app/src/util/getMainGeomType.js
Uploading a custom layer, the client will now look at the predominant GeoJSON feature type, and render the GL layer accordingly. Supports:
- polygon (`fill`)
- lines (`line`)
- points (`circle`) 
Workspace `udw-v2-12a70761-3661-44ad-90a9-981418e7b857` shows an example of the 3 types together:
Fixes https://github.com/GlobalFishingWatch/map-client/issues/989
Custom layers could be further improved with
<a href="https://github.com/GlobalFishingWatch/map-client/issues/991">Support different geometry types within a single custom layer</a> 
<a href="https://github.com/GlobalFishingWatch/map-client/issues/992">Support for labels in custom layers</a>
> Adds support for line and point custom layers

- CHANGELOG.md
- app/src/encounters/components/EncountersInfo.jsx
- app/src/map/mapInteractionActions.js
- app/src/recentVessels/components/RecentVesselItem.jsx
- app/src/vesselInfo/components/VesselInfoDetails.jsx
Fixed timestamp displays to be in UTC rather than local time (in VIIRS info, hover tooltips, and encounters panel). Also added 'UTC' in plain text to display datetimes to remove any potential ambiguity.
This can be merged to master.
Closes https://github.com/GlobalFishingWatch/map-client/issues/999
> UTC timestamp display

- app/src/layers/customLayerActions.js
`GetMap` actually requires layer names, not layer indexes, which for some reason still worked with our test WMS endpoint.
> Fixed error in layers names in WMS GetMap query

- README.md
- app/src/timebar/components/Timebar.jsx
Set `window.extendedMaxTimeRange = true` in the console to extend the max time range to 2 years.
> Add console switch for extended max time range

- CHANGELOG.md
- app/src/activityLayers/components/ActivityLayers.jsx
- app/src/activityLayers/components/TracksLayer.jsx
- app/src/vesselInfo/vesselInfoActions.js
- app/src/workspace/workspaceActions.js
Fixes an issue where a vessel track and info would be loaded twice when having it both pinned and displayed in a given workspace.
Seems to fix #1006
> Fixed loading vessel twice from workspace

- public/index.html
Mark `map` as canonical URL to avoid duplicates for different workspaces in google results.
> use canonical url and https to load meta

- bin/retrieve-workspace.js
- package.json
- src/app/constants.js
- src/app/encounters/encountersActions.js
- src/app/layers/layersActions.js
- src/app/map/components/HoverPopup.jsx
- src/app/map/components/MapWrapper.jsx
- src/app/map/containers/MapWrapper.js
Adds support for a Mapbx GL powered encounters layer.
Needs https://github.com/GlobalFishingWatch/map-components/pull/56
Although this is experimental, I'd like to merge as it fixes several issues.
The workspace layer that needs to be used:
```
{
'id': 'encounters_ais',
'visible': true,
'interactive': true,
'color': '#eeff00',
"url": "https://api-dot-skytruth-pelagos-production.appspot.com/v2/tilesets/gfw-task-673-encounters-v3",
"type": "CartoDBAnimation",
"label": "Encounters",
},
```
We will need to generalize the behaviour created for encounters to all interactive time-series layer based on Mapbox GL:
- loading of headers 
- needs adding an headerURL field to workspace.json
- refactor workspace format entirely now? (https://github.com/GlobalFishingWatch/map-client/issues/871)
- …
> Encounters mapboxgl

- src/app/search/components/SearchPanel.jsx
Seems that google translator plugin does unexpected things in the DOM and breaks react flow.
This keeps the same <li> element for the message to fix it.
> Fix google translate plugin crash

- documentation/env_variables.md
- src/app/mapPanels/leftControlPanel/components/LeftControlPanel.jsx
- src/app/mapPanels/leftControlPanel/components/Loader.jsx
- src/app/mapPanels/leftControlPanel/components/ZoomControls.jsx
- src/app/mapPanels/leftControlPanel/components/leftControlPanel.module.scss
- src/app/mapPanels/leftControlPanel/components/zoomControls.module.scss
- src/styles/components/shared/language-selector.module.scss
Spinner was working properly but sometimes and due its absolute styles it was overlapped by the language selector. This PR fixes it positioning the elements in the same container.
> Don't overlap language selector with loading spinner

- package.json
- src/app/map/containers/MapWrapper.js
- yarn.lock
Ports the heatmap layer feature opacity change from develop.
Uses map-components v2.2.16, which has legacy tracks removed in favour of geojson tracks, but without the new timebar
> Legacy tracks to geojson without timebar

- src/app/components/Shared/LanguageSelector.jsx
Use fallback interval to check when bablic doesn't return the languages list to fix https://github.com/GlobalFishingWatch/GFW-Tasks/issues/1161
> set interval fallback to check bablic languages list

- package.json
- yarn.lock
This will load tiles at a lower zoom level than before, which results in
- much better performance and much less UI lock
- the aggregation grid is more visible, depending on the zoom level 
- points look smaller, depending on the zoom level (sadly fixing that is much less trivial than just setting a diameter value)
**important** The initial workspace zoom level has an impact on the initial UI performance:
- if set to 4, it will load z level 3
- if set to 4.0001, it will load z level 4
In the first case, we have the best panning performance before zooming in (least points visible per screen area), in the second case we have worst panning performance but better zooming in performance (more points visible from the get go but further zooming in won't load a new zoom level)
> lower heatmap res

- src/app/map/containers/MapWrapper.js
To fix https://github.com/GlobalFishingWatch/gfw-eng-tasks/issues/21 but not introduce a breaking change updating the title for the fishing effort layer this PR includes a new field in the workspace called `tooltip` with original `title` fallback.
Once this is merged the default workspace in dev and production should be updated to add the line: ```"tooltip": "Apparent fishing effort",```
> use tooltip field in workspace

- package.json
- src/app/map/components/HoverPopup.jsx
> I'm having a problem with the public map.. I've seen this issue in the past, but I don't remember what we did with this. For some reason when clicking on a cluster (negative value) the client is trying to get vessel info from that negative value instead of saying "There are multiple vessels here, zoom in"... on some cases it works properly, you see the magnifying glass but for some others it does not:
Fixes that ☝️ with this https://github.com/GlobalFishingWatch/map-components/releases/tag/3.0.9
> Clusters fix
