GlobalFishingWatch/map-client

- app/src/components/map.jsx
- config/webpack.config.js
> Add google maps api key

- public/form/css/styles.css
- public/form/login.html
- public/form/registration.html
- public/form/thankyou.html
> Static SF pages fixes

- app/src/components/layers/canvasLayer.jsx
- app/src/components/map.jsx
> display vessels on timeline

- app/src/components/map.jsx
- app/styles/index.scss
CSS and readability improvements
> CSS and readability improvements

- app/src/components/button_box_slider.jsx
- app/src/components/footer.jsx
> Fix footer

- app/src/components/shared/header.jsx
- app/styles/components/c_menu.scss
> add dropdown menu

- app/src/components/layers/canvasLayer.jsx
> golden ships with white fake trails

- app/styles/components/c_menu.scss
> fix menu styles

- app/src/components/map.jsx
Time range rendering improvement
> Time range rendering improvement

- app/src/components/map/layer_panel.jsx
- app/styles/base/colors.scss
- app/styles/base/text.scss
- app/styles/components/c_accordion.scss
- app/styles/components/c_layer_panel.scss
- package.json
> Map accordeon styles

- app/src/components/map/layer_panel.jsx
The PR fixes an issue where the user couldn't toggle the layers anymore.
> Fixes an issue where the layers couldn't be toggled

- app/src/components/layers/canvas_layer.jsx
- app/src/components/map.jsx
Not really sure this is a move in the right direction, but it does fix an issue I found: if you moved the map during paused playback, the new tiles would load with all points.
> Move playback range to canvas component

- app/src/actions/map.js
- app/src/components/map.jsx
- app/src/reducers/filters.js
- public/workspace-2.json
Improve time limit propagation
> Improve time limit propagation

- package.json
> Fix SVG react import

- app/src/components/map/Timeline.jsx
- app/src/components/map/TogglePauseButton.jsx
This implements play/pause functionality on the timeline.
Outer extent boundaries are taken into account, so if during play the inner extent goes at the end of the outer extent, it will translate autoamtically.
> Timeline play/pause

- app/src/components/map/Timebar.jsx
- app/src/constants.js
This was mentioned by @clementprdhomme here https://github.com/Vizzuality/GlobalFishingWatch/pull/93#issuecomment-237822698
> Fix the frozen outer handle issue

- app/src/actions/contact.js
- app/src/actions/map.js
- app/src/actions/user.js
- app/src/components/contact_us/contact_us_form.jsx
- app/src/components/contact_us/support_form.jsx
- app/src/components/layers/canvas_layer.jsx
- app/src/components/map.jsx
title says it all, changes are all very brainless too (zoooommmbiiieee PR)
remember to update your .env if you havent by now, otherwise a lot of things will stop working
> Extract API endpoint URL to env var

- .sass-lint.yml
- app/src/components/shared/header.jsx
- app/styles/_settings.scss
- app/styles/components/c-menu.scss
- app/styles/components/shared/c-header.scss
update menu styles and fix errors dropwdown
> update menu styles and fix errors dropwdown

- app/src/components/articles_publications.jsx
- app/src/components/blog.jsx
- app/src/components/blog_detail.jsx
- app/src/components/contact_us.jsx
- app/src/components/definitions.jsx
- app/src/components/faq.jsx
- app/src/components/partners.jsx
- app/src/components/privacy_policy.jsx
- app/src/components/shared/CoverPrimary.jsx
- app/src/components/shared/CoverSecondary.jsx
- app/src/components/shared/header.jsx
- app/src/components/terms_of_use.jsx
- app/src/components/the_project.jsx
- app/src/components/tutorials.jsx
- app/styles/components/c-cover-page.scss
- app/styles/components/shared/c-header.scss
> [WIP] Feature/cover blog pages tiago

- app/src/components/layers/track_layer.jsx
- app/src/components/map/DurationPicker.jsx
- app/src/components/map/Timebar.jsx
- app/styles/_layout-settings.scss
- app/styles/components/c_map.scss
- app/styles/components/map/c-durationpicker.scss
- app/styles/components/map/c-timeline.scss
Doesn't actually let user pick the duration, only shows it, but I wanted this merged before working on something else.
> [WIP] Added duration picker to timeline

- app/src/actions.js
- app/src/actions/articlesPublications.js
- app/src/components/ArticlesPublications.jsx
- app/src/containers/ArticlesPublications.js
- app/src/index.jsx
- app/src/reducers/articlesPublications.js
- app/src/routes.jsx
- public/articles-publications.json
Articles and publications content
> Articles and publications content

- .env.sample
- .eslintrc
- app/src/actions/articlesPublications.js
- app/src/actions/blog.js
- app/src/actions/contact.js
- app/src/actions/definitions.js
- app/src/actions/faq.js
- app/src/actions/map.js
- app/src/actions/search.js
- app/src/actions/vesselInfo.js
- app/src/components/MapIFrame.jsx
- app/src/routes.jsx
- config/webpack.config.js
Add map embed; extract config vars
> Add map embed; extract config vars

- app/src/components/MapIFrame.jsx
This PR removes an unwanted vertical scroll on the iframe used for the map.
> Removes an unwanted vertical scroll on the iframe

- app/src/actions.js
- app/src/actions/blog.js
- app/src/components/Blog.jsx
- app/src/components/Blog/Pagination.jsx
- app/src/components/Shared/CoverPrimary.jsx
- app/src/containers/Blog.js
- app/src/reducers/blog.js
- app/styles/components/c-pagination-blog.scss
Actually working pagination.
Loads page count from API and renders paginator accordingly.
Support URL /blog?page=<int> to load specific page
> Blog pagination

- app/src/components/ContactUs.jsx
- app/src/components/ContactUs/ContactUsForm.jsx
- app/styles/_settings.scss
- app/styles/components/c-button.scss
- app/styles/components/c-contact-form.scss
- app/styles/components/c-contact.scss
- app/styles/components/shared/c-header.scss
> Update styles for contact form

- app/src/components/ArticlesPublications.jsx
- app/src/components/Blog.jsx
- app/src/components/BlogDetail.jsx
- app/src/components/Definitions.jsx
- app/src/components/FAQ.jsx
- app/src/components/Shared/Loader.jsx
- app/styles/components/c-loader.scss
Add spinner to:
- Blog page
- Blog detail page
- FAQ page
- Definition page
- Articles page
> Add spinner component

- app/src/components/MapIFrame.jsx
- app/src/components/Shared/FooterMini.jsx
- app/styles/_settings.scss
- app/styles/components/shared/c-footer-mini.scss
> IFrame map footer

- app/src/components/Shared/CoverPrimary.jsx
- app/src/components/Shared/CoverSecondary.jsx
- app/styles/components/c-cover-page.scss
Need to review the new margin bottom values with the designer
> Remove LDF logo from subpage headers

- app/src/components/FAQ.jsx
- app/styles/_base.scss
- public/faq.json
> added section headings to FAQ

- app/src/components/Map/NoLogin.jsx
- app/styles/components/map/c-no-login.scss
Still very far from designs, lmk if you want me to go there
> map login back button

- app/src/components/ContactUs.jsx
- app/src/components/ContactUs/ContactUsForm.jsx
- app/src/containers/ContactUs.js
in the contact form, when logged in, name and email filled in by default
> Name and email filled in by default

- app/src/components/MapIFrame.jsx
- app/src/components/Shared/Header.jsx
- app/src/components/Shared/MenuMobile.jsx
- app/styles/_base.scss
- app/styles/_settings.scss
- app/styles/components/c-map.scss
- app/styles/components/c-mobile-menu.scss
- app/styles/components/shared/c-header.scss
We still need share icon (is asked in a Pivotal task) and design for logged user in mobile menu (that's why I commented this zone for the time being..)
> implemented mobile menu in map page and iframe

- app/styles/components/shared/c-header.scss
fix header in map page to allow click in the maximum space possible.
> set width auto

- app/src/components/Shared/MenuMobile.jsx
- app/styles/components/c-mobile-menu.scss
Updates based on @clementprdhomme 's comments on closed PR (https://github.com/Vizzuality/GlobalFishingWatch/pull/174)
> replaced span elements for buttons

- .env.sample
- .eslintrc
- README.md
- app/src/components/Map.jsx
- app/src/components/MapIFrame.jsx
- config/webpack.config.js
If set to false, you can see the map without being logged in
> Require login on map feature flag

- app/src/components/Partners.jsx
- app/src/components/Partners/ContactUsSection.jsx
- app/styles/components/c-partner-section.scss
- app/styles/components/c-partners-contact-us.scss
> partners contact us

- app/src/components/Home/CoverPage.jsx
- app/src/components/Home/CoverPagePreloader.jsx
Preloads home slider images by attaching them to an invisible element.
> preload home slider images

- app/src/components/ContactUs/ContactUsForm.jsx
- app/styles/components/c-contact-form.scss
- invalid form could be submitted in Safari: fixed
- added a red border on invalid form fields
- form could be submitted when question type was not selected: fixed
> fixed contact us form validation

- app/styles/_base.scss
- public/faq.json
Change faq.json with the underline link class.
> Update link styles on faq page

- app/src/components/Home/Steps.jsx
- app/src/components/Orbcomm.jsx
- app/src/components/Shared/ToolTip.jsx
- app/src/components/Shared/ToolTipJSON.jsx
- app/src/components/TheProject.jsx
- app/styles/base/normalize.scss
- app/styles/components/c-tooltip-info.scss
https://www.pivotaltracker.com/story/show/129452389
> better tooltips for mobile

- app/src/components/MapIFrame.jsx
- app/src/components/Shared/Header.jsx
- app/styles/components/c-map.scss
This PR fixes an issue where the header would be apart from the (iframe) map.
It also improves the detection of the header's active item by taking into account trailing slashes or nested paths. For example, going to `/faq` or `/faq/` has no effect on it.
Related task: [https://www.pivotaltracker.com/story/show/129376711](https://www.pivotaltracker.com/story/show/129376711)
> Fixes the position of the header on the iframe and improves the header

- app/styles/_base.scss
- app/styles/components/shared/c-header.scss
> fix hamburger menu on map

- app/src/components/Orbcomm.jsx
- app/src/components/Shared/ToolTip.jsx
Brings back the on mouse out behavior of the tooltip on desktop.
> Fix tooltips on desktop

- app/src/actions/user.js
- app/styles/components/c-funder-section.scss
- app/styles/components/c-research-section.scss
Change:
- Partner page responsive styles
- Cover pages responsive styles
WIP => Because I need new designs for some components on partner pages
> Responsive styles for partner page and cover pages

- app/src/components/Shared/FooterMini.jsx
- app/styles/components/shared/c-footer-mini.scss
Everything's in the title.
[Pivotal task](https://www.pivotaltracker.com/story/show/129468127)
> Slightly increases the size of Oceana's logo in the mini footer

- app/styles/components/c-publication-article.scss
Task => https://www.pivotaltracker.com/story/show/129552759
> Responsive implementation of Articles and Publications

- public/articles-publications.json
This PR updates the case of the titles of the articles and publications so they match the design.
[Pivotal Task](https://www.pivotaltracker.com/story/show/129829651)
> Changes to title case for the titles of the articles

- app/src/components/ContactUs/ContactUsForm.jsx
Task => https://www.pivotaltracker.com/story/show/129043553
> Fix message contact logic

- app/styles/components/homepage/c-steps.scss
Task => https://www.pivotaltracker.com/story/show/129783433
> Fix responsive styles on IOS and Safari browser

- app/styles/components/c-mobile-menu.scss
Task => https://www.pivotaltracker.com/story/show/129915759
> fix color on menu for resposnive styles

- app/styles/components/c-mobile-menu.scss
This PR makes the scroll smooth inside the mobile drawer on an iOS device.
[Pivotal Task](https://www.pivotaltracker.com/story/show/129918589)
> Makes the scroll smooth in the mobile drawer

- app/styles/components/c-funder-section.scss
- app/styles/components/c-other-section.scss
Task => https://www.pivotaltracker.com/story/show/129829825
> fix responsive styles on partner page

- app/styles/components/c-cover-page.scss
Task => https://www.pivotaltracker.com/story/show/130001677
> Fix slider on home page

- app/src/components/Shared/FooterMini.jsx
- app/styles/components/c-map.scss
- app/styles/components/shared/c-container-footer.scss
- app/styles/components/shared/c-footer-mini.scss
Task => https://www.pivotaltracker.com/story/show/129831571
There are elements that not exist on zeplin. 
We are redesign small footer on this task => https://www.pivotaltracker.com/story/show/129919439
> update responsive styles for small footer and logic

- app/src/components/ArticlesPublications.jsx
- app/styles/components/shared/c-modal.scss
- app/styles/layout/l-static-page.scss
Update:
- Modal window.
- Articles and Publication titles.
- Video width on tutorial page.
Task => https://www.pivotaltracker.com/story/show/129945125
> Update responsive styles

- app/src/components/Shared/ToolTip.jsx
Task => https://www.pivotaltracker.com/story/show/130019423
> Change links on tooltip component

- app/src/components/Shared/CoverPrimary.jsx
- app/styles/components/c-cover-page.scss
- app/styles/components/c-research-section.scss
Task => https://www.pivotaltracker.com/story/show/130082217
> fix cover-sub-pages fix

- app/src/components/TheProject.jsx
- app/styles/layout/l-static-page.scss
Task => https://www.pivotaltracker.com/story/show/130174015
> Add videos and content to about the project page

- app/src/components/Home/CoverPage.jsx
- app/styles/components/c-cover-page.scss
Change min-height to Leo-Slider for small and medium devices and fix infinite slider.
Task => https://www.pivotaltracker.com/story/show/130101437
Task 2 => https://www.pivotaltracker.com/story/show/130101325
> fix slider for small devices

- app/src/components/Home/CoverPage.jsx
- app/styles/components/c-cover-page.scss
Change LDF logo width when change the slider.
Task=>https://www.pivotaltracker.com/story/show/130174367
> Change logo width on sliders

- app/src/components/ContactUs/ContactUsForm.jsx
- app/styles/components/c-contact.scss
Task => https://www.pivotaltracker.com/story/show/130174377
> Add new content to contact page

- app/src/components/Shared/Footer.jsx
- app/styles/components/c-footer.scss
Task => https://www.pivotaltracker.com/story/show/130174351
> Update responsive footer with new styles

- app/styles/components/shared/c-modal.scss
Task => https://www.pivotaltracker.com/story/show/130216715
> Fix support modal error on IOS

- app/src/components/Shared/Footer.jsx
Task => https://www.pivotaltracker.com/story/show/130174351
> Delete "funding text" on footer

- app/src/components/ResearchProgram.jsx
Task => https://www.pivotaltracker.com/story/show/130174503
> Add italic words

- app/src/components/Map/SupportForm.jsx
- app/styles/components/c-support-form.scss
Task => https://www.pivotaltracker.com/story/show/130267829
> update styles for support form

- app/src/components/Partners/PartnerSection.jsx
- app/styles/components/c-partner-section.scss
Need @danielcasius to accept the design.
Task => https://www.pivotaltracker.com/story/show/130263023
> Add new content to partner page

- app/styles/components/c-contact.scss
Task => https://www.pivotaltracker.com/story/show/130174377
> Change emails text on contact page

- app/styles/components/c-cover-page.scss
Task => https://www.pivotaltracker.com/story/show/130295887
> add cursor pointer to buttons on slider

- app/src/components/Shared/Header.jsx
Task => https://www.pivotaltracker.com/story/show/130277413
> Delete share button

- app/assets/icons/close.svg
- app/styles/components/shared/c-modal.scss
Task => https://www.pivotaltracker.com/story/show/130297429
> Update svg and add cursor pointer to close button on modal

- app/src/components/ResearchProgram.jsx
- app/src/components/TheProject.jsx
- app/styles/layout/l-static-page.scss
Task => https://www.pivotaltracker.com/story/show/130284105
> Update quotes styles on project an research pages

- app/src/components/ContactUs.jsx
- app/styles/components/c-button.scss
- app/styles/components/c-contact-form.scss
Task => https://www.pivotaltracker.com/story/show/130298803
> fix styles for message after contact page

- app/src/components/Definitions.jsx
- app/src/components/Shared/Accordion.jsx
- app/src/lib/Utils.jsx
- app/styles/components/shared/c-content-accordion.scss
Task => https://www.pivotaltracker.com/story/show/129786629
Task (2) => https://www.pivotaltracker.com/story/show/129829309 (when you open now an accordion item, title is on top)
> Improve accordion logic on mobile

- app/styles/components/c-support-form.scss
Task => https://www.pivotaltracker.com/story/show/130352651
> fix disabled styles on IOS

- app/styles/components/c-partner-section.scss
Task => https://www.pivotaltracker.com/story/show/130360983
> update width logos on partner page

- app/src/components/ContactUs/ContactUsForm.jsx
Task => https://www.pivotaltracker.com/story/show/130361053
> Change logic contact-page-form

- app/src/components/Shared/Header.jsx
- app/styles/components/shared/c-header.scss
Add three dots to large user names on the header.
> fix user name header

- app/src/components/Shared/Modal.jsx
Task => https://www.pivotaltracker.com/story/show/130370757
> update logic for modal

- app/src/actions/contact.js
- app/src/components/ContactUs/ContactUsForm.jsx
- app/src/components/Map/SupportForm.jsx
- app/src/components/Shared/FooterMini.jsx
- app/styles/components/c-contact-form.scss
- app/styles/components/c-support-form.scss
Task => https://www.pivotaltracker.com/story/show/130350287
> Fix close button on mesage after support contact

- app/src/components/Shared/Header.jsx
Task => https://www.pivotaltracker.com/story/show/130389055
Now, we only write the first part of the name.
But if that is so long, the best solution is put three dots.
> update logic for username on header

- app/src/components/Shared/FooterMini.jsx
- app/styles/components/shared/c-container-footer.scss
Task => https://www.pivotaltracker.com/story/show/130299223
> update styles for small devices

- app/src/components/Definitions.jsx
Task => https://www.pivotaltracker.com/story/show/130369375
Is a new version of => https://github.com/Vizzuality/GlobalFishingWatch/pull/324
> fix scrolling issues on description page

- app/src/actions/search.js
- app/src/actions/vesselInfo.js
- app/src/components/Layers/VesselsTileData.js
- app/src/constants.js
Works more or less, but a lot of tiles give 404 (API side) which the clients handles super badly (annoying issue on our side that I struggle to fix)
> added new tilesets endpoints

- app/src/components/Layers/VesselsLayerOverlay.js
- app/src/components/Layers/VesselsLayerTiled.js
Fixes a critical map rendering issue where vessel points would appear 'stuck' while panning the map.
> fix frozen vessels issue

- app/src/components/Layers/VesselsLayerTiled.js
- app/src/components/Layers/VesselsTileData.js
- app/src/constants.js
This fixes the issue where not all points were rendered using the new endpoints (covering 5 years instead of 2)
> fixed data parsing with new endpoints

- app/styles/components/c-map.scss
Pivotal Task: https://www.pivotaltracker.com/story/show/134420395
> removed attributions from map

- app/src/components/Map/Timebar.jsx
"A small PR for man, one giant leap for mankind"
> fix the "timeline jump" issue

- app/styles/components/map/c-layer-panel.scss
Pivotal task: https://www.pivotaltracker.com/story/show/134422291
> Added many enhacements to opacity selectors

- app/src/actions.js
- app/src/actions/map.js
- app/src/components/Map.jsx
- app/src/components/Map/BasemapPanel.jsx
- app/src/components/Map/LayerInfo.jsx
- app/src/components/Map/LayerItem.jsx
- app/src/components/Map/LayerPanel.jsx
- app/src/containers/Map.js
- app/src/containers/Map/BasemapPanel.jsx
- app/src/containers/Map/LayerInfo.jsx
- app/src/containers/Map/LayerPanel.jsx
- app/src/reducers/map.js
- app/styles/components/map/c-layer-info.scss
- public/workspace.json
Pivotal task: https://www.pivotaltracker.com/story/show/134922495
> Implemented layer info modal for layers

- app/src/components/Map/Timebar.jsx
with this, the duration picker updates as you drag the inner extents
> Improve duration picker behavior

- app/src/components/Map.jsx
- app/styles/components/c-control_panel.scss
- app/styles/components/c-map.scss
Pivotal task: https://www.pivotaltracker.com/story/show/136095157
> Added attributions on map for mobile

- app/src/components/Map/NoLogin.jsx
- app/styles/components/map/c-no-login.scss
Changes have designer's approval.
> Fixed no-login modal styles

- app/src/components/Map.jsx
- app/src/components/Shared/Modal.jsx
This system avoid modals overlap each other giving a z-index value to everyone need it and solves problem with the two modals when layer library is being used.
> Added z-index system to modal component

- app/src/components/Layers/MapLayers.jsx
the zoomed in heat map style was not applied
> fixed zoomed heat map style

- app/styles/components/c-map.scss
- app/styles/components/c-mobile-menu.scss
This PR fixes reported errors from Enrique like timebar overlapping mobile menu and fixed map container overflow.
> Fixed some overflow issues

- app/src/components/Map/ControlPanel.jsx
- app/styles/_settings.scss
- app/styles/components/c-control_panel.scss
- app/styles/components/c-vessel-info-panel.scss
- app/styles/components/map/c-pinned-tracks.scss
> Added overflow scroll to panel control

- app/src/components/Map.jsx
- app/src/components/Shared/Modal.jsx
- app/styles/components/map/c-prompt-layer.scss
- app/styles/components/shared/c-modal.scss
> Rework delete layer prompt modal

- public/testIFrame.html
Unless I'm mistaken there's actually nothing to do on our side.
> test iframe page

- app/src/components/Map.jsx
- app/styles/components/c-map.scss
https://www.pivotaltracker.com/story/show/136899151
> lat lon on hover

- app/src/components/Layers/HeatmapSubLayer.js
- app/src/components/Map/ControlPanel.jsx
- app/src/components/Map/VesselInfoPanel.jsx
- app/src/components/Shared/ExpandButton.jsx
- app/styles/_settings.scss
- app/styles/components/c-vessel-info-panel.scss
- app/styles/components/shared/c-expand-button.scss
> Added expand option to vesselInfo

- app/src/actions/heatmap.js
- app/src/actions/helpers/heatmapTileData.js
- app/src/actions/vesselInfo.js
- app/src/components/Layers/GLContainer.js
- app/src/components/Layers/HeatmapLayer.js
- app/src/components/Layers/HeatmapSubLayer.js
- app/src/components/Layers/MapLayers.jsx
- app/src/components/Layers/TiledLayer.js
- app/src/components/Layers/TracksLayer.js
This aims at fixing once and for all offset issues by using world coordinates for heatmap and tracks instead of unreliable pixel offsets
> Fix offsets

- app/src/components/Map/FilterPanel.jsx
- app/styles/components/shared/c-selector.scss
- move emoji at the end of the country name (keyboard accessibility)
- added a css rule that might fix the white on white country list on linux
@tiagojsag could you test on your machine?
> country list fixes

- app/src/reducers/vesselInfo.js
if you are on edit mode (pinned vessels) and disable it, there's currently an error. this fixes it
> Fix pinned vessel edit close

- app/styles/components/map/c-layer-list.scss
- app/styles/components/shared/c-toggle.scss
Fixes issue where icons in list-item would jump to another line.
> changes margins to prevent line break

- app/src/components/Map/PinnedTracks.jsx
- app/styles/components/map/c-pinned-tracks.scss
This PR adds a heading to the pinned vessels accordion.
> feature: pinned vessels text

- app/src/components/Layers/MapLayers.jsx
- app/src/components/Layers/TracksLayer.js
- app/src/constants.js
This PR includes the following changes:
- Changes hover thickness and style on depending on zoom level.
> feature: track hover zoom styles

- app/src/components/Map/FilterItem.jsx
- app/src/components/Map/LayerBlendingOptionsTooltip.jsx
- app/src/components/Map/LayerItem.jsx
- app/src/components/Map/PinnedTracksItem.jsx
- app/styles/components/map/c-layer-blending.scss
This PR fixes the issue where tooltip weren't closing on click outside of them.
> close pinned vessels tooltip

- app/src/components/Map/LayerBlendingOptionsTooltip.jsx
- app/styles/components/c-control_panel.scss
- app/styles/components/c-map.scss
- app/styles/components/map/c-custom-layer.scss
- app/styles/components/map/c-flag-filters.scss
- app/styles/components/map/c-form.scss
- app/styles/components/map/c-layer-library.scss
- app/styles/components/map/c-layer-management-modal.scss
- app/styles/components/shared/c-modal.scss
This PR intends to fix following issues:
- Adds overflow on countries filter.
- Improves general look and feel of the modal in mobile.
- Includes fluid webkit modal scroll on accordion.
- adds on touchend evento to close tooltip on mobile.
- Moves events from `componentDidMount` to `componentWillUpdate` because on mobile having all blending icons add a `touchend` event to the window blcoked the ui.
> Feature: responsiveness-ness-ness

- app/src/components/Map/CustomLayer.jsx
- app/styles/components/map/c-custom-layer.scss
This PR adds a caption to the upload layer form to indicate that you need to paste a link to a`.kml` file
> Feat: custom layer form caption

- app/styles/components/map/c-layer-management-modal.scss
- app/styles/components/shared/c-modal.scss
This PR fixes some styles to set min-height in the modal and to prevent weird scrolling in mobile.
> fixes modal height

- README.md
- app/src/actions/user.js
- app/src/components/Map.jsx
- app/src/constants.js
Refactor login system and add role to see map
> Refactor login system and add role to see map

- app/src/components/Map/DurationPicker.jsx
- app/src/constants.js
... also in the duration picker menu item.
> display 1 month instead of one month

- app/styles/components/c-control_panel.scss
- app/styles/components/c-map-panels.scss
- app/styles/components/map/c-report-panel.scss
Fixes an issue when interacting with the right side of the map was not possible.
> fixed map interaction

- app/styles/components/map/c-report-panel.scss
Fixes clipping of button in report panel.
> fixes padding when only child in polygon-list

- app/src/components/Map/ControlPanel.jsx
- app/src/containers/Map/ControlPanel.js
- app/src/containers/Map/LayerItem.js
- app/styles/components/c-control_panel.scss
- package.json
This PR includes the following:
**Bonus**
- DRY code refacto
> feat: fishing hours tooltip

- app/src/actions/helpers/heatmapTileData.js
- app/src/actions/vesselInfo.js
- app/src/components/Layers/TracksLayer.js
- app/src/constants.js
I just reproduced the previous version's behaviour for now.
> show fishing activity on tracks

- app/src/actions/map.js
- app/src/actions/workspace.js
- app/src/components/Layers/GLContainer.js
- app/src/components/Layers/MapLayers.jsx
- app/src/components/Map.jsx
- app/src/reducers/map.js
Fixes 'tracks jump' when zooming or panning.
Aditionally, enhances zoom to cluster transition by batching zoom and map center change.
> fixed tracks jump

- app/src/components/Map/WelcomeModal.jsx
- app/styles/components/map/c-welcome-modal.scss
- app/styles/components/shared/c-modal.scss
Test with the following html:
```
<p>
<b>Welcome to Global Fishing Watch 2.0! We’ve updated our look and added some new features. Now you can:</b>
</p>
<ul>
<li>Adjust the time period you are viewing with the slider at the bottom of the screen by clicking/dragging the beginning/end points.</li>
<li>Zoom in and out with the plus/minus signs in the upper left hand corner.</li>
<li>Click on a point on the heat map to reveal a vessel track.</li>
</ul>
<p>Check out our new  <a target="_blank" href="http://globalfishingwatch.org/tutorials">tutorial video</a> to learn more.</p>
```
> fixed welcome modal styles

- CHANGELOG.md
- app/styles/components/map/c-welcome-modal.scss
- app/styles/components/shared/c-modal.scss
> better welcome modal for large screens

- CHANGELOG.md
- app/src/components/Map.jsx
- app/styles/_settings.scss
- app/styles/components/c-control_panel.scss
- app/styles/components/c-map-panels.scss
Fixes 
https://basecamp.com/1756858/projects/12049853/todos/306729800
https://www.pivotaltracker.com/story/show/144017757 / https://basecamp.com/1756858/projects/12049853/todos/303918857
> fixed sidebar scrolling issues

- CHANGELOG.md
- app/src/actions/filters.js
- app/src/actions/workspace.js
- app/src/components/Map/DatePicker.jsx
- app/src/components/Map/Timebar.jsx
- app/src/containers/Map/Timebar.js
- package.json
https://basecamp.com/1756858/projects/12049853/todos/307445725
Aditionnally, adds a year selector.
> Fix date pickers

- CHANGELOG.md
- app/src/components/App.jsx
- app/src/components/Layers/GLContainer.js
- app/styles/_settings.scss
- app/styles/components/c-app.scss
> Fallback canvas renderer

- .env.sample
- .eslintrc
- CHANGELOG.md
- README.md
- app/src/components/App.jsx
- app/src/components/Shared/Header.jsx
- app/src/containers/App.js
- app/styles/components/c-app.scss
- app/styles/components/shared/c-header.scss
- config/webpack.config.js
- public/literals.json
> Dismissable legacy banner

- app/styles/components/shared/c-modal.scss
> fixed welcome modal

- app/src/actions/helpers/heatmapTileData.js
- app/src/actions/workspace.js
- app/src/components/Layers/MapLayers.jsx
- public/workspace_vms.json
- public/workspace_vms_2.json
- there was an issue with the workspace, since both heatmap layers had the same layer id.
- I added handling of mismatch between columnIds available on tileset headers vs columns that are actually available in every tile, which seemed to happen at some point.
> fixed loading of AIS/VMS workspace

- app/src/actions/helpers/heatmapTileData.js
- app/src/components/Layers/HeatmapSubLayer.js
This makes sure that, when filtering by flag on the heatmap rendering, we check for the existence of the "category" data before accessing it.
> Only filter by flag on layers that have category field

- .eslintrc
- CHANGELOG.md
- app/src/actions/layers.js
- app/src/actions/search.js
- app/src/containers/Map/ControlPanel.js
- app/src/containers/Map/RecentVesselsModal.js
- app/src/containers/Map/SearchPanel.js
- app/src/containers/Map/SearchResult.js
- app/src/containers/Map/VesselInfoPanel.js
Pending clarification on https://basecamp.com/1756858/projects/12049853/todos/310630456
> Search on added but disabled fishing effort layers

- app/src/actions/search.js
- app/src/actions/vesselInfo.js
- app/src/components/Map/CustomLayer.jsx
- app/src/components/Map/SearchResult.jsx
- app/src/reducers/vesselInfo.js
- app/src/util/getVesselName.js
- public/workspace_vms.json
https://basecamp.com/1756858/projects/12049853/todos/310476197
> Use header priorities to determine pinned vessel lable

- app/src/actions/heatmap.js
- app/src/actions/helpers/heatmapTileData.js
- app/src/components/Layers/GLContainer.js
- app/src/components/Layers/HeatmapSubLayer.js
Removed a part of the vessels frames that was not needed
> removed seriesUid

- app/src/components/Map/DatePicker.jsx
- app/styles/components/map/datepicker.scss
- package-lock.json
- package.json
MIssing
- the <input> needs to be disabled, so the user cannot write the date
- the calendar picker needs to be positioned properyl
> Replace date picker

- app/src/components/App.jsx
- app/src/index.jsx
Google analytics was not sending time on page or pageview data for the map
> Move ga init to app and specify pathname

- app/assets/icons/play.svg
- app/src/timebar/components/DatePicker.jsx
- app/src/timebar/components/Timebar.jsx
- app/src/timebar/components/TogglePauseButton.jsx
- app/styles/components/control_panel.scss
- app/styles/components/map-panels.scss
- app/styles/components/map.scss
- app/styles/components/map/datepicker.scss
- app/styles/components/map/timebar.scss
- app/styles/icons.scss
> Timebar changes

- app/src/mapPanels/leftControlPanel/components/MiniGlobe.jsx
setState can never be called on the constructor
> Fix mini-globe warning

- app/src/actions/workspace.js
- app/src/filters/filtersActions.js
- app/src/filters/filtersReducer.js
Save the timeline speed setting in the workspace. Refactor the speed reducer
> Save speed in workspace

- app/src/filters/components/FilterGroupForm.jsx
- app/styles/_settings.scss
- app/styles/components/shared/color-picker.scss
- Add missing red color, maintain orange
- Add id for color picker in filter group modal
> Red color was missing and filter modal color picker id

- app/index.html
Change the old description
```
Global Fishing Watch enables anyone with an Internet connection to see fishing activity anywhere in the ocean in near real-time — for free
```
with the one according to GFW 2.0 vision:
```
Through our free and open data transparency platform, Global Fishing Watch enables research and innovation in support of ocean sustainability.
```
Also changed `Global Fishing Watch` title and description on the social media and title with `Global Fishing Watch | Sustainability through Transparency` to meet the GFW v2 vision.
> Changes on title and metadata to meet GFW v2.0 vision

- app/styles/components/shared/header.scss
This fixed an issue where layers would not be accessible in mobile version.
> fixed layers button in mobile version

- app/src/siteNav/components/Footer.jsx
- app/src/siteNav/components/MenuMobile.jsx
NOTE: Do not merge, this PR is just for review purpose.
GFW has a new WP site with new pages, we have changed the side menu and footer to match the new urls. 
@tiagojsag @nerik could you please check if I have modified the links in the correct place? I will merge the PR once you have approved it and once we are certain there is no wrong link in the new menu/footer.
> Modify links in footer and menu to match the one in the new WP site

- app/src/actions/heatmap.js
- app/src/constants.js
- app/src/encounters/components/EncountersInfo.jsx
- app/src/encounters/encountersActions.js
- app/src/layers/layersActions.js
- app/src/util/heatmapTileData.js
- app/src/workspace/workspaceActions.js
Connects https://github.com/GlobalFishingWatch/GFW-Tasks/issues/543
> Encounters layer

- app/src/components/Layers/CustomLayerWrapper.js
- app/src/components/Layers/MapLayers.jsx
- app/src/layers/layersReducer.js
- app/src/workspace/workspaceActions.js
> Do not let KML loading resize viewport except on layer add

- app/src/encounters/components/EncountersVessel.jsx
- app/src/encounters/encountersActions.js
- app/src/encounters/encountersReducer.js
- app/src/search/searchActions.js
- app/src/util/getVesselName.js
- app/src/vesselInfo/containers/VesselInfoPanel.js
- app/src/vesselInfo/vesselInfoActions.js
- app/src/vesselInfo/vesselInfoReducer.js
See https://github.com/GlobalFishingWatch/GFW-Tasks/issues/688#issuecomment-376642119
Tested search, vessel info, and encounters on the problematic workspace, works fine.
> use API header.info.fields instead of header.vesselFields

- app/src/encounters/components/EncountersPanel.jsx
- app/styles/_settings.scss
- app/styles/components/control_panel.scss
- app/styles/components/info-panel.scss
Fix for https://github.com/GlobalFishingWatch/GFW-Tasks/issues/687
> fixed scroll + collapsed encounters on mobile

- app/src/config.js
- app/src/encounters/components/EncountersInfo.jsx
Fix for https://github.com/GlobalFishingWatch/GFW-Tasks/issues/691
> add encounter time

- app/src/util/getPBFTile.js
- app/src/util/heatmapTileData.js
Fix for https://github.com/GlobalFishingWatch/GFW-Tasks/issues/705
> Send auth header when fetching PBF tiles

- app/src/constants.js
- app/src/search/components/SearchResult.jsx
- app/src/search/searchActions.js
Fix for https://github.com/GlobalFishingWatch/GFW-Tasks/issues/712
Fix for https://github.com/GlobalFishingWatch/GFW-Tasks/issues/711
> Fixed encounters/search related issues

- app/src/actions/heatmap.js
- app/src/components/App.jsx
- app/src/containers/App.js
- app/src/reducers/heatmap.js
- public/literals.json
Fixes https://github.com/GlobalFishingWatch/GFW-Tasks/issues/751
> Deprecated layers notifications

- app/src/search/searchActions.js
Currently blocked by two issues on the API.
- I can't get multi tileset search to work.
Single tileset returns 37 results:
`https://api-dot-skytruth-pleuston.appspot.com/v2/tilesets/gfw-tasks-657-uvi-v2/search/?query=bol&limit=14&offset=0`
Same query, 2 tilesets give 0 results:
`https://api-dot-skytruth-pleuston.appspot.com/v2/tilesets/gfw-tasks-657-uvi-v2,indo-public-fishing/search/?query=bol&limit=14&offset=0`
- we're going to need to integrate the `tilesetId` in each search result, in order to call the correct endpoint when clicking on each search result.
> multiple tilesets search endpoint

- app/src/activityLayers/components/ActivityLayers.jsx
- app/src/map/components/Map.jsx
- app/src/map/gl-styles/style.json
- app/styles/components/map.scss
- app/styles/components/map/map-footer.scss
Per requested in https://github.com/GlobalFishingWatch/GFW-Tasks/issues/842
> added Google logo and attribution

- app/src/activityLayers/components/ActivityLayers.jsx
- app/src/activityLayers/components/TracksLayer.jsx
- app/src/activityLayers/containers/ActivityLayers.js
- app/src/tracks/tracksActions.js
- app/src/tracks/tracksReducer.js
- app/src/vessels/components/Vessel.jsx
- app/src/vessels/containers/Vessel.js
> highlight tracks on panel hover

- app/src/components/Shared/ColorPicker.jsx
- app/src/config.js
- app/src/vesselInfo/vesselInfoReducer.js
- app/src/vessels/components/Vessel.jsx
Adds more colors for tracks, and automatic color cycling (every new track gets assigned a different color)
> tracks colors cycling (fixes #953)

- app/src/activityLayers/components/HeatmapSubLayer.js
Avoids UI lock by deleting unneeded sprites very progressively.
> better pooling management (fixes #961)

- app/src/components/Shared/Icon.jsx
- app/src/components/Shared/Icon.scss
- app/src/mapPanels/rightControlPanel/components/ControlPanel.jsx
- app/src/mapPanels/rightControlPanel/components/SubMenu.jsx
- app/styles/components/shared/accordion.scss
- app/styles/components/submenu.scss
Following designs specified in  https://github.com/GlobalFishingWatch/map-client/issues/941
> Replaced subpanel back button by close button

- CHANGELOG.md
- app/src/app/appActions.js
- app/src/app/appReducer.js
- app/src/map/components/MapDashboard.jsx
- app/src/map/containers/MapDashboard.js
- app/src/vesselInfo/vesselInfoActions.js
Fix for issue explained here:
https://github.com/GlobalFishingWatch/map-client/issues/941
> Automatically open right panel when clicking on a vessel

- app/src/config.js
- app/src/vesselInfo/vesselInfoReducer.js
Fix for https://github.com/GlobalFishingWatch/map-client/issues/964
Checked with Juanca and ended up implementing the solution described here: https://github.com/GlobalFishingWatch/map-client/issues/964#issuecomment-422029300
> Fixed autocycling tracks color

- app/src/activityLayers/components/ActivityLayers.jsx
- app/src/activityLayers/heatmapActions.js
- app/src/activityLayers/heatmapTilesActions.js
- adds support for touch devices 
- when a tile has not finished loading, allow querying for vessels on the tile immediately above (zoom - 1) or below (z + 1).
> Map interaction fixes

- app/src/map/gl-styles/style.json
* Removed the MPAAtlas layer. 
* Changed the old `mpant` to use a subset of `WPDA` dataset.
* Changed the old `mparu` to use a subset of `WPDA` dataset.
* Added `WDPA` ID to `protected` planet.
> Change the MPAs in the styles.json

- CHANGELOG.md
- app/src/app/appActions.js
- app/src/components/Shared/ColorPicker.jsx
- app/src/config.js
- app/src/constants.js
- app/src/layers/components/CustomLayer.jsx
- app/src/layers/components/LayerItem.jsx
- app/src/layers/components/LayerManagementModal.jsx
- app/src/layers/components/LayerPanel.jsx
- app/src/layers/containers/CustomLayer.js
- app/src/layers/customLayerActions.js
- app/src/layers/customLayerReducer.js
- app/src/layers/layersActions.js
- app/src/layers/layersReducer.js
- app/src/map/gl-styles/style.json
- app/src/map/mapInteractionActions.js
- app/src/map/mapStyleActions.js
- app/src/workspace/workspaceActions.js
- app/styles/components/map/form.scss
- config/webpack.config.js
- package-lock.json
- package.json
Tested with:
- GeoJSON: some polygons around french Brittany - https://gist.githubusercontent.com/nerik/74a7f7d5b6c907cbb4a0b5b6de675e58/raw/dd360106e74f5c7db3eb00734468820e70c34e77/map.geojson
- WMS: Protected planet - http://gis.unep-wcmc.org:6080/arcgis/services/wdpa/public/MapServer/WMSServer
- Raster: NASA VIIRS - http://map1.vis.earthdata.nasa.gov/wmts-webmerc/VIIRS_CityLights_2012/default//GoogleMapsCompatible_Level8/{z}/{y}/{x}.jpg
> Custom layers improvements

- app/src/activityLayers/components/TracksLayer.jsx
Fixes https://github.com/GlobalFishingWatch/GFW-Tasks/issues/974
> Removed series filtering from tracks layer

- app/src/components/Shared/LanguageSelector.jsx
- config/webpack.config.js
- package-lock.json
To avoid crashes this PR check when bablic was loaded to request and render languages selector.
Bonus: order languages by key alphabetically to ensure the same order on change.
> Bablic fix

- app/src/layers/components/CustomLayer.jsx
- app/src/layers/customLayerActions.js
- package-lock.json
Fixes https://github.com/GlobalFishingWatch/map-client/issues/1022
This was happening because the 'temporary' layer object created on the custom layer reducer was not updated when commiting custom layer changes.
> Fix custom layer

- package.json
- src/app/basemap/basemapReducer.js
- src/app/map/components/MapWrapper.jsx
- src/app/map/components/mapDashboard.module.scss
- src/app/notifications/notificationsActions.js
- src/app/utils/isWebGLSupported.js
- src/app/vesselInfo/vesselInfoActions.js
- src/app/vessels/containers/Vessel.js
- yarn.lock
See https://github.com/GlobalFishingWatch/map-components/pull/43, to improve also get the webGL function checker from pixi repo and copy into utils, this avoids import the whole library just to check it.
Release map-components and update version before merging 🙏 
Before (white screen for longer):
Now:
> Map dynamic import

- CHANGELOG.md
- package.json
- yarn.lock
> Update version 4.0.0

- src/app/map/containers/MapWrapper.js
Fixes https://github.com/GlobalFishingWatch/GFW-Tasks/issues/1045
> Send custom layer url to static layers list

- CHANGELOG.md
- package.json
- src/app/search/components/SearchPanel.jsx
- yarn.lock
- Fix results list
- Updates changelog and package.json version
> Fix results list

- src/app/components/Shared/LanguageSelector.jsx
- src/app/layers/components/LayerItem.jsx
- src/styles/components/map/layer-item.module.scss
Adds a label with the same content as the input so bablic translates it, we show the label and hide the input. When user clicks "edit layers", we change the input value with the translated content of the label so user can edit from the right language.
> Adds a label to layer inputs so bablic can translate their names

- src/app/layers/components/LayerItem.jsx
- src/styles/components/map/layer-item.module.scss
- yarn.lock
Fix label styles and remove pointer events none when no edit mode to help bablic to focus on the element.
> fix layers label styles

- package.json
- src/app/config.js
- src/app/map/containers/MapWrapper.js
- yarn.lock
> Lower legacy heatmap layers opacity when activating a track

- src/app/filters/components/FilterGroupItem.jsx
- src/styles/components/shared/react-select.module.scss
- yarn.lock
Fixes https://github.com/GlobalFishingWatch/GFW-Tasks/issues/1142
Fixes issue with out of focus filter values selector in filter modal.
> fixed filter style issues

- src/app/filters/filtersReducer.js
Filters highlight track range to be bound by inner range.
> fixed highlighting track out of inner range

- src/app/map/components/StaticLayerPopup.jsx
Open popup links in new tab as per ProtectedSeas team suggestion.
> open popup in new tab

- package.json
Closes https://github.com/GlobalFishingWatch/GFW-Tasks/issues/1157
Changes the repo https://github.com/georgzoeller/iso-3166-1-alpha-2/pull/3/files with our own to change the `Taiwan, Province of China` with `Chinese Taipei`
> Change the flag library to the GFW fork

- cloudbuild-PR.yaml
- nginx/nginx.conf
cloudbuild and nginx.conf were using old config, this PR includes:
- Fix routes path
- Enable html5 mode
> nginx html5 mode

- package.json
- yarn.lock
Replaces gtiles tiles URL 🤷‍♂️
> fix gtiles

- package.json
- yarn.lock
See 
https://github.com/uber/react-map-gl/issues/550
https://github.com/GlobalFishingWatch/map-components/releases/tag/3.0.7
> fix mapbox warning

- src/app/layers/layersActions.js
- src/app/layers/layersReducer.js
- src/app/map/containers/MapWrapper.js
- src/app/workspace/workspaceActions.js
- yarn.lock
> Custom GeoJSON issues

- src/app/analytics/analyticsActions.js
- src/app/analytics/analyticsMiddleware.js
- src/app/layers/components/LayerItem.jsx
- src/app/layers/containers/LayerItem.js
- src/styles/components/map/layer-item.module.scss
Closes https://github.com/GlobalFishingWatch/gfw-eng-tasks/issues/91
> disabled reports tooltip

- package.json
- src/app/map/containers/MiniGlobe.js
- yarn.lock
Update components with new version from [monorepo](https://github.com/GlobalFishingWatch/frontend/tree/master/packages/ui-components):
while mapModule is a depreacted component from [map-components](https://github.com/GlobalFishingWatch/map-components)
> use new components

- package.json
- src/app/map/containers/MapWrapper.js
- src/app/user/userActions.js
- yarn.lock
Fix crash when using [workspace indonesia-tnc-1](https://globalfishingwatch.org/map/workspace/indonesia-tnc-v1)
🤷
> fix crash when headers response error
